name: Workflow for Codecov example-python

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests and collect coverage
      run: |
        pytest --cov=app --cov-report=xml  # Gera o relatório de cobertura em XML

    - name: Check coverage.xml file
      run: |
        if [ -f coverage.xml ]; then echo "Coverage file exists"; else echo "Coverage file does not exist"; fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true
        files: coverage.xml  # Especifica o arquivo de cobertura
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
